### PR TITLE
Module should also work on RHEL8 hosts

### PR DESCRIPTION
**Pull request by markasammut**

### CODE REVIEW

**Comment by bschonec** [comment]
Please accept the merge request.

**Comment by markasammut** [comment]
@benformosa Can you please merge this?

**Comment by benformosa** [comment]
@markasammut, thanks for letting me know this was here. I had no idea anyone else was using this module.
I've uploaded a [new version 1.1.0 to Puppet Forge](https://forge.puppet.com/modules/benformosa/linux_disable_ipv6/1.1.0) including your change.

**Comment by markasammut** [comment]
@benformosa Thanks!

**Pull request merged**
